/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'lubiedak' at '3/20/17 8:45 PM' with Gradle 2.14.1
 *
 * @author lubiedak, @date 3/20/17 8:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
